### ISSUE TITLE
Issue when using with gulp cached

### ISSUE THREAD

**Issue by Dylan-Chapman** [jedrichards/gulp-jscodesniffer#1]
I'm using this module in conjunction with gulp-cached. If I save on a file that has no changes (so gulp-cached doesn't pass the file down the stream),  jscodesniffer fails and kicks the error:

```
..."node_modules\gulp-jscodesniffer\reporters\default.js:17
 files failed jscodesniffer\n'),this.jscs.failCount,this.jscs.results.length);
                                                                     ^
TypeError: Cannot read property 'length' of undefined"
```

It's strange because I've never had a plugin than ran into errors in this scenario.

**Comment by jedrichards** [comment]
Thanks for taking the time to post an issue :)

I wrote this plugin well over a year ago now, and I don't think its seen much use or popularity, and I haven't updated it at all. I'd say its basically abandoned, sorry :S

I'm not even sure how much love the parent project jscodesniffer is getting, especially considering the popularity of eslint these days. Maybe you would be better off switching to eslint for your linting and style checking needs? I'm sure there's a good Gulp plugin.

I'd be happy to merge a pull request if you manage to sort out the problem though.

**Comment by Dylan-Chapman** [comment]
To be honest, I'd never even heard of eslint! I'm a little late to the scene I suppose and jscodesniffer was one of the first things to show up for checking JS code consistency. 

You're right, there is a Gulp plugin for eslint.

Thank you for the help!

**Comment by jedrichards** [comment]
No probs :)
